name: 'Diary Converter'
description: 'Convert development diary logs to Zenn articles with optimized formatting for project documentation'
author: 'centervil'

# Example usage:
# - name: Convert Development Diary
#   uses: centervil/Diary-Converter@main
#   with:
#     source_file: 'dev-records/2025-03-26-development.md'
#     destination_file: 'articles/2025-03-26-dev-diary.md'
#     api_key: ${{ secrets.GOOGLE_API_KEY }}
#     model: 'gemini-2.0-flash-001'
#     project_name: 'Diary-Converter'
#     issue_number: '1'
#     prev_article: 'dev-diary'

inputs:
  source_file:
    description: 'Path to the source diary file'
    required: true
  destination_file:
    description: 'Path to the destination article file'
    required: true
  api_key:
    description: 'Gemini API Key'
    required: true
  model:
    description: 'Gemini model to use'
    required: false
    default: 'gemini-2.0-flash-001'
  template:
    description: 'Template file path'
    required: true
  debug:
    description: 'Enable debug mode'
    required: false
    default: 'false'
  # project_name と issue_number は diary_converter.py から削除されたため不要
  prev_article:
    description: 'Previous article slug for related links section (without date prefix, e.g. "dev-diary" not "2025-03-25-dev-diary")'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Prepare output directory
      run: |
        mkdir -p $(dirname ${{ github.workspace }}/${{ inputs.destination_file }})
      shell: bash

    - name: Run Diary Converter
      run: |
        cd ${{ github.action_path }}
        
        # Debug mode flag
        DEBUG_FLAG=""
        if [ "${{ inputs.debug }}" = "true" ]; then
          DEBUG_FLAG="--debug"
          echo "Debug mode enabled"
        fi
        
        # Construct the full template path using GITHUB_ACTION_PATH and set it as env var
        FULL_TEMPLATE_PATH="${GITHUB_ACTION_PATH}/${{ inputs.template }}"
        echo "Setting TEMPLATE_PATH environment variable to: ${FULL_TEMPLATE_PATH}"
        echo "TEMPLATE_PATH=${FULL_TEMPLATE_PATH}" >> $GITHUB_ENV

        # project_name と issue_number の検出・設定ロジックは不要になったため削除
        
        # Previous article slug for related links section
        # Example: If previous article is "2025-03-25-dev-diary.md", use "dev-diary"
        PREV_ARTICLE_ARG=() # Initialize as an empty array
        if [ -n "${{ inputs.prev_article }}" ]; then
          PREV_ARTICLE_ARG=(--prev-article "${{ inputs.prev_article }}")
          echo "Using previous article: ${{ inputs.prev_article }}"
        fi
        
        # Set API key
        export GOOGLE_API_KEY="${{ inputs.api_key }}"
        
        echo "Converting ${{ inputs.source_file }} to ${{ inputs.destination_file }}"
        echo "Using model: ${{ inputs.model }}"
        
        # Prepare arguments for Python script using bash array
        PYTHON_ARGS=(
          "${{ github.workspace }}/${{ inputs.source_file }}"
          "${{ github.workspace }}/${{ inputs.destination_file }}"
          --model "${{ inputs.model }}"
        )
        # Add optional flags/arguments if they exist
        [ "${{ inputs.debug }}" = "true" ] && PYTHON_ARGS+=(--debug)
        # PROJECT_NAME_ARG と ISSUE_NUMBER_ARG は削除
        [ ${#PREV_ARTICLE_ARG[@]} -gt 0 ] && PYTHON_ARGS+=("${PREV_ARTICLE_ARG[@]}")
        # Template argument is now passed via environment variable

        echo "Executing Python script with arguments:"
        echo "${PYTHON_ARGS[@]}"

        # Execute Python script directly with array expansion
        PYTHONPATH=${{ github.action_path }}/src python -m diary_converter.diary_converter "${PYTHON_ARGS[@]}"
      shell: bash
      # TEMPLATE_PATH is now set via GITHUB_ENV in the script above

    - name: Process Generated Document
      run: |
        cd ${{ github.action_path }}
        
        # Debug mode flag
        DEBUG_FLAG=""
        if [ "${{ inputs.debug }}" = "true" ]; then
          DEBUG_FLAG="--debug"
          echo "Debug mode enabled for document processing"
        fi
        
        echo "Processing generated document to fix common LLM output issues..."
        PYTHONPATH=${{ github.action_path }}/src python -m diary_converter.document_processor \
          "${{ github.workspace }}/${{ inputs.destination_file }}" \
          $DEBUG_FLAG
        
        echo "Document processing completed"
      shell: bash

    - name: Verify Output
      run: |
        if [ -f "${{ github.workspace }}/${{ inputs.destination_file }}" ]; then
          echo "✅ Conversion and processing successful: ${{ inputs.destination_file }}"
          wc -l "${{ github.workspace }}/${{ inputs.destination_file }}"
        else
          echo "❌ Conversion failed: File not created"
          exit 1
        fi
      shell: bash

branding:
  icon: 'book'
  color: 'blue'
