version: '3.8'

services:
  diary-converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diary-converter
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
      - ./templates:/app/templates
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PYTHONPATH=/app
    working_dir: /app 